--
-- Thorsten Bruhns (Thorsten.Bruhns@opitz-consulting.de)
-- $Id: server.sql 10 2008-11-11 10:25:06Z oracle $
--
-- Infos for shared server processes
--

SELECT DECODE(TOTALQ, 0, 'No Requests',
    WAIT/TOTALQ || ' HUNDREDTHS OF SECONDS') "AVERAGE WAIT TIME PER REQUESTS"
    FROM V$QUEUE
    WHERE TYPE = 'COMMON'; 

SELECT MAXIMUM_CONNECTIONS "MAX CONN", MAXIMUM_SESSIONS "MAX SESS",
    SERVERS_STARTED "STARTED", SERVERS_TERMINATED "TERMINATED",
    SERVERS_HIGHWATER "HIGHWATER"
    FROM V$SHARED_SERVER_MONITOR; 

SELECT NAME "NAME", PADDR, REQUESTS,
 (BUSY/(BUSY + IDLE)) * 100 "%TIME BUSY", STATUS
 FROM V$SHARED_SERVER;


